# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: "Update Nimbus Experiments"

on:
  # schedule:
  #   - cron: '*/30 * * * *'
  pull_request: {}

jobs:
  update-nimbus-experiments:
    name: "Update Nimbus Experiments"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Main Branch"
        uses: actions/checkout@v2
        with:
          path: fenix
          ref: main
      - name: "Update Experiments JSON"
        id: update-experiments-json
        uses: jeddai/update-initial-experiments@v1
        with:
          repo-path: fenix
          output-path: app/src/main/res/raw/initial_experiments.json
          experimenter-url: https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v6/experiments/?is_first_run=true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: steps.update-experiments-json.outputs.changed == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: fenix
          branch: automation/test-experiments-update
          commit-message: "update initial_experiments.json based on the current first-run experiments in experimenter"
          title: "Update initial experiments JSON for Nimbus"
          body: "This (automated) PR updates the initial_experiments.json on the `main` branch"
